### ISSUE TITLE
用aiotg开发一个telegram爬虫机器人 · yangsoon

### ISSUE THREAD

**Issue by yangsoon** [yangsoon/yangsoon.github.io#15]
https://yangsoon.github.io/2018/04/14/%E7%94%A8aiotg%E5%BC%80%E5%8F%91%E4%B8%80%E4%B8%AAtelegram%E7%88%AC%E8%99%AB%E6%9C%BA%E5%99%A8%E4%BA%BA/

**Comment by perkfly** [comment]
有一个 proxy 写错啦

**Comment by yangsoon** [comment]
@yifeikong 对不起 能不能指出哪里错了 我改一下

**Comment by yangsoon** [comment]
@yifeikong 我知道了 我以为你说代码写错了 我里面有一个单词拼错了
